baseurl: "https://brunoluiz.net"
title: "Bruno Luiz Silva"
theme: 'hugo-PaperMod'
languageCode: "en-us"
enableEmoji: true
paginate: 7
params:
  title: Bruno Luiz Silva
  description: A collection of random software engineering thoughts
  images:
  - android-chrome-512x512.png
  defaultTheme: 'auto'
  homeInfoParams:
    Title: üë®‚Äçüíª Bruno Luiz Silva
    Content: A collection of random software engineering thoughts
  socialIcons: # optional
    - name: "email"
      url: "mailto:contact@brunoluiz.net"
    - name: "github"
      url: "https://github.com/brunoluiz"
    - name: "twitter"
      url: "https://twitter.com/brunoluiz"
    - name: "linkedin"
      url: "https://uk.linkedin.com/in/brnluiz"
  ShowReadingTime: true
